### ISSUE TITLE
UnicodeDecodeError in interp string from SNe_16_phot_1.db file

### ISSUE THREAD

**Issue by gnarayan** [astrofoley/astr596#5]
Error running the command listed in `useful_composites.txt` file using the db file from @msiebert1 

```bash
(snspec) gnarayan@hugin|~/work/astr596/src> python query_db.py 19 "SELECT * FROM Supernovae where phase between -1.5 and -1" "SELECT * FROM Supernovae where phase between -2 and -1.5" "SELECT * FROM Supernovae where phase between -2.5 and -2" "SELECT * FROM Supernovae where phase between -3 and -2.5" "SELECT * FROM Supernovae where phase between -3.5 and -3" "SELECT * FROM Supernovae where phase between -4 and -3.5" "SELECT * FROM Supernovae where phase between -4.5 and -4" "SELECT * FROM Supernovae where phase between -5 and -4.5" "SELECT * FROM Supernovae where phase between -5.5 and -5" "SELECT * FROM Supernovae where phase between -6 and -5.5" "SELECT * FROM Supernovae where phase between -6.5 and -6" "SELECT * FROM Supernovae where phase between -7 and -6.5" "SELECT * FROM Supernovae where phase between -7.5 and -7" "SELECT * FROM Supernovae where phase between -8 and -7.5" "SELECT * FROM Supernovae where phase between -8.5 and -8" "SELECT * FROM Supernovae where phase between -9 and -8.5" "SELECT * FROM Supernovae where phase between -10 and -9" "SELECT * FROM Supernovae where phase between -11 and -10" "SELECT * FROM Supernovae where phase < -11"
SQL Query: SELECT * FROM Supernovae where phase between -1.5 and -1
```

**TRACKBACK**
```python
Traceback (most recent call last):
  File "query_db.py", line 253, in <module>
    composites.append(composite.main(query_strings[n], boot))
  File "/Users/gnarayan/work/astr596/src/composite.py", line 811, in main
    SN_Array = grab(Full_query)
  File "/Users/gnarayan/work/astr596/src/composite.py", line 115, in grab
    interp       = msg.unpackb(row[16])
  File "/Users/gnarayan/anaconda2/envs/snspec/lib/python2.7/site-packages/msgpack_numpy.py", line 187, in unpackb
    return _unpacker.unpackb(packed, encoding=encoding, **kwargs)
  File "msgpack/_unpacker.pyx", line 139, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:2068)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x97 in position 6: invalid start byte
```

It's possible this is a package version issue, but I don't think so, but since there's no `requirement.txt` I can't be sure. Here's my conda environment file. 

**ENVIRONMENT**
```bash
(snspec) gnarayan@hugin|~/work/astr596/src> conda env export
name: snspec
channels:
- mpi4py
- defaults
- http://ssb.stsci.edu/astroconda
- conda-forge
dependencies:
- lmfit=0.9.7=py27_0
- astropy=2.0.1=np113py27_0
- cycler=0.10.0=py27_0
- freetype=2.5.5=2
- functools32=3.2.3.2=py27_0
- icu=54.1=0
- libpng=1.6.30=1
- matplotlib=2.0.2=np113py27_0
- mkl=2017.0.3=0
- numpy=1.13.1=py27_0
- openssl=1.0.2l=0
- pip=9.0.1=py27_1
- py=1.4.34=py27_0
- pyparsing=2.2.0=py27_0
- pyqt=5.6.0=py27_2
- pytest=3.2.1=py27_0
- python=2.7.13=0
- python-dateutil=2.6.1=py27_0
- pytz=2017.2=py27_0
- qt=5.6.2=2
- readline=6.2=2
- scipy=0.19.1=np113py27_0
- setuptools=27.2.0=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- subprocess32=3.2.7=py27_0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.11=0
- specutils=0.2.2=py27_1
- pip:
  - msgpack-numpy==0.4.1
  - msgpack-python==0.4.8
  - pyfits==3.4
  - pyyaml==3.12
  - speclite==0.5
prefix: /Users/gnarayan/anaconda2/envs/snspec
```

**Comment by msiebert1** [comment]
This is a package version issue. You need msgpack-python==0.4.6 and you might need msgpack-numpy==0.3.5 (but I have an undergrad who claims it works with 0.3.6).

**Comment by msiebert1** [comment]
Also useful_composites.txt is pretty old now. I now store a lot of metadata in a separate table so that query might not work. You will need to do a join on that table:
python query_db.py nb "SELECT * from Supernovae inner join Photometry ON Supernovae.SN = Photometry.SN where phase between -1.5 and -1"
